# Generated by Django 4.0.1 on 2022-06-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerTable',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('customerName', models.CharField(max_length=50)),
                ('customerImage', models.ImageField(blank=True, default='', upload_to='media/')),
                ('customerDob', models.DateField()),
                ('customerGender', models.CharField(max_length=15)),
                ('customerEmail', models.EmailField(max_length=100)),
                ('customerMobile', models.CharField(max_length=20)),
                ('customerAddress', models.CharField(max_length=120)),
                ('customerCity', models.CharField(default='', max_length=50)),
                ('customerState', models.CharField(default='', max_length=50)),
                ('customerPincode', models.CharField(default='', max_length=20)),
                ('customerUsername', models.CharField(max_length=50)),
                ('customerPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
