# Generated by Django 4.0.1 on 2022-06-15 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_rename_customermobile_customertable_customermobilenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedbackTable',
            fields=[
                ('feedbackId', models.AutoField(primary_key=True, serialize=False)),
                ('feedbackType', models.CharField(max_length=20)),
                ('feedbackDescription', models.TextField()),
                ('feedbackResponse', models.TextField()),
                ('feedbackStatus', models.CharField(max_length=20)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customertable')),
            ],
        ),
    ]
