# Generated by Django 4.0.1 on 2022-07-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_feedbacktable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbacktable',
            name='feedbackResponse',
            field=models.TextField(blank=True),
        ),
    ]
