# Generated by Django 4.0.1 on 2022-06-02 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('booking', '0001_initial'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='paymentTable',
            fields=[
                ('paymentId', models.AutoField(primary_key=True, serialize=False)),
                ('paymentAmount', models.FloatField()),
                ('paymentDate', models.DateField(auto_now_add=True)),
                ('paymentTime', models.TimeField(auto_now_add=True)),
                ('paymentMode', models.CharField(max_length=50)),
                ('paymentStatus', models.CharField(max_length=50)),
                ('cardNumber', models.BigIntegerField()),
                ('cardExpiryMonth', models.IntegerField()),
                ('cardExpiryYear', models.IntegerField()),
                ('cvvNumber', models.IntegerField()),
                ('nameOnCard', models.CharField(max_length=50)),
                ('bookingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingtable')),
            ],
        ),
        migrations.CreateModel(
            name='allStatusTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentStatus', models.CharField(max_length=20)),
                ('bookingStatus', models.CharField(max_length=20)),
                ('bookingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingtable')),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customertable')),
                ('paymentId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.paymenttable')),
            ],
        ),
    ]
