# Generated by Django 4.0.1 on 2022-06-02 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookingTable',
            fields=[
                ('bookingId', models.AutoField(primary_key=True, serialize=False)),
                ('bookingDateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('bookingStartDate', models.DateField()),
                ('bookingEndDate', models.DateField()),
                ('bookingDays', models.IntegerField()),
                ('bookingStatus', models.CharField(blank=True, max_length=50)),
                ('customerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customertable')),
                ('venueId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venue.venuetable')),
            ],
        ),
        migrations.CreateModel(
            name='danceFloorTable',
            fields=[
                ('danceFloorId', models.AutoField(primary_key=True, serialize=False)),
                ('danceFloorType', models.CharField(max_length=50)),
                ('danceFloorDescription', models.CharField(default='', max_length=250)),
                ('danceFloorImage', models.ImageField(blank=True, default='', upload_to='media/')),
                ('danceFloorPricePerBooking', models.FloatField()),
                ('danceFloorCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='foodTable',
            fields=[
                ('foodId', models.AutoField(primary_key=True, serialize=False)),
                ('foodName', models.CharField(max_length=50)),
                ('foodImage', models.ImageField(blank=True, default='', upload_to='media/')),
                ('foodCuisine', models.CharField(max_length=50)),
                ('foodPricePerServing', models.FloatField()),
                ('foodCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='customerFoodTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingtable')),
                ('foodId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.foodtable')),
            ],
        ),
        migrations.CreateModel(
            name='customerDanceFloorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookingtable')),
                ('danceFloorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.dancefloortable')),
            ],
        ),
    ]
