# Generated by Django 4.0.1 on 2022-06-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingtable',
            name='eventType',
            field=models.CharField(default='', max_length=150),
        ),
    ]
