# Generated by Django 4.0.1 on 2022-06-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminTable',
            fields=[
                ('adminId', models.AutoField(primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=50)),
                ('adminDob', models.DateField()),
                ('adminGender', models.CharField(max_length=15)),
                ('adminDesignation', models.CharField(max_length=50)),
                ('adminEmail', models.EmailField(max_length=100)),
                ('adminMobile', models.CharField(max_length=20)),
                ('adminAddress', models.CharField(max_length=120)),
                ('adminImage', models.ImageField(blank=True, default='', upload_to='media/')),
                ('adminUsername', models.CharField(max_length=50)),
                ('adminPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
