# Generated by Django 4.0.1 on 2022-06-03 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='adminTable',
            new_name='administratorTable',
        ),
    ]
