# Generated by Django 4.0.1 on 2022-06-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_rename_admintable_administratortable'),
    ]

    operations = [
        migrations.CreateModel(
            name='messageTable',
            fields=[
                ('messageId', models.AutoField(primary_key=True, serialize=False)),
                ('messageDate', models.DateField(auto_now_add=True)),
                ('senderName', models.CharField(max_length=50)),
                ('senderEmail', models.EmailField(max_length=100)),
                ('messageStatus', models.CharField(max_length=50)),
                ('senderMessage', models.TextField()),
            ],
        ),
    ]
