# Generated by Django 4.0.1 on 2022-06-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_messagetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administratortable',
            old_name='adminMobile',
            new_name='adminMobileNumber',
        ),
        migrations.AddField(
            model_name='administratortable',
            name='adminContactCountryCode',
            field=models.CharField(default='', max_length=10),
        ),
    ]
