# Generated by Django 4.0.1 on 2022-06-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_rename_adminmobile_administratortable_adminmobilenumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administratortable',
            name='adminDob',
            field=models.DateField(null=True),
        ),
    ]
