# Generated by Django 4.0.1 on 2022-07-22 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_administratortable_admindob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administratortable',
            old_name='adminContactCountryCode',
            new_name='adminMobileCountryCode',
        ),
    ]
