# Generated by Django 4.0.1 on 2022-06-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventTable',
            fields=[
                ('eventTypeId', models.IntegerField(primary_key=True, serialize=False)),
                ('eventType', models.CharField(max_length=100)),
                ('eventDescription', models.TextField()),
                ('eventTypeCode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='venueTable',
            fields=[
                ('venueId', models.AutoField(primary_key=True, serialize=False)),
                ('venueName', models.CharField(max_length=100)),
                ('venueDescription', models.TextField()),
                ('venueCity', models.CharField(max_length=50)),
                ('venueState', models.CharField(max_length=50)),
                ('venueAddress', models.CharField(max_length=120)),
                ('venueContact', models.CharField(max_length=20)),
                ('venueEmail', models.EmailField(max_length=100)),
                ('venueCapacity', models.IntegerField()),
                ('venueImage', models.ImageField(default='', upload_to='media/')),
                ('venuePrice', models.FloatField()),
                ('venueRating', models.FloatField()),
            ],
        ),
    ]
