# Generated by Django 4.0.1 on 2022-06-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuetable',
            name='venueContact',
        ),
        migrations.AddField(
            model_name='venuetable',
            name='venueContactCountryCode',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='venuetable',
            name='venueContactNumber',
            field=models.CharField(default='', max_length=20),
        ),
    ]
