# Generated by Django 4.0.1 on 2022-06-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_alter_eventtable_eventtypeid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='eventTable',
        ),
    ]
