from django.urls import path
from administrator import views


urlpatterns = [
    path('', views.adminLoginForm),
    path('message/', views.addMessage),
    path('allmessages/', views.showAllMessages),
    path('changemsgstatus/',views.changeMessageStatus),
    path('signupform/', views.adminSignupForm),
    path('dashboard/', views.adminDashboard),
    path('manageaccount/', views.showAccountDetails),
    path('saveaccountdetails/', views.saveAccountDetails),
    path('adminsignupform/', views.adminSignupForm),
    path('dologin/', views.adminLoginValidate),
    path('dologout/', views.adminLogout),
    path('viewalladministrator/', views.viewAllAdmin),
    path('addadministratorform/',views.showAddAdministratorForm),
    path('addadministrator/',views.addAdministrator),
    path('editadministrator/<int:admin_id>/',views.showEditAdministratorPage),
    path('updateadministrator/', views.updateAdministrator),
    path('deleteadministrator/<int:admin_id>/',views.deleteAdministrator),
    path('viewallcustomer/', views.viewAllCustomer),
    path('addcustomerform/', views.showAddCustomerForm),
    path('addcustomer/', views.addCustomer),
    path('editcustomer/<int:customer_id>/', views.showEditCustomerPage),
    path('updatecustomer/', views.updateCustomer),
    path('deletecustomer/<int:customer_id>/', views.deleteCustomer),
    path('addvenueform/', views.showAddVenueForm),
    path('addvenue/', views.addVenue),
    path('viewallvenue/', views.viewAllVenue),
    path('editvenue/<int:venue_id>/',views.showEditVenuePage),
    path('updatevenue/',views.updateVenue),
    path('deletevenue/<int:venue_id>/',views.deleteVenue),
    path('viewallbooking/',views.viewAllBooking),
    path('addfoodform/',views.showAddFoodForm),
    path('addfood/',views.addFood),
    path('deletefood/<int:food_id>/',views.deleteFood),
    path('editfood/<int:food_id>/',views.editFoodDetails),
    path('updatefood/', views.updateFoodDetails),
    path('viewallfood/',views.viewAllFood),
    path('adddancefloorform/',views.showAddDanceFloorForm),
    path('adddancefloor/',views.addDanceFloor),
    path('editdancefloor/<int:dancefloor_id>/', views.showEditDanceFloorPage),
    path('updatedancefloor/', views.updateDanceFloorDetails),
    path('deletedancefloor/<int:dancefloor_id>/', views.deleteDanceFloor),    
    path('viewalldancefloor/',views.viewAllDanceFloor),
    path('viewallpayment/',views.viewAllPayment),
    path('viewallinvoice/',views.viewAllInvoice),
    path('viewallfeedback/',views.viewAllFeedback),
    path('feedbackresponseform/<int:feedback_id>/',views.feedbackResponseForm),
    path('submitfeedbackresponse/', views.submitFeedbackResponse),
]
